#define MESHLINK_VEHICLE_ID 0x03
#define MESHLINK_GROUND_STATION_ID 0x00

#define MESHLINK_PROTOCOL_VERSION 0x04
#define MESHTASTIC_SERIAL Serial2
#define MAVLINK_SERIAL Serial5
#define MAVLINK_BRIDGE_SYS_ID 0xff
#define MAVLINK_BRIDGE_COMP_ID 0x68
#define MESHTASTIC_CHANNEL_INDEX 1
#define MESHTASTIC_PORTNUM_TEXT 1
#define MESHTASTIC_PORTNUM_POSITION 3
#define MESHTASTIC_PORTNUM_TIME 69
#define MESHTASTIC_PORTNUM_MESHLINK 369
#define MESHTASTIC_BROADCAST_ADDR 0xFFFFFFFFUL
#define MESHTASTIC_PORTNUM_UNKNOWN 0

#define TELEMETRY_PERIOD_MS 20000       // time between telemetry packets in milliseconds

#define LOITER_DIRECTION 0              //   0 = clockwise, 1 = counter-clockwise
#define LOITER_RADIUS 10.0f            // loiter radius in meters