#define MESHLINK_VEHICLE_ID 0x01
#define MESHTASTIC_SERIAL Serial2
#define MAVLINK_SERIAL Serial5
#define MAVLINK_BRIDGE_SYS_ID 0xff
#define MAVLINK_BRIDGE_COMP_ID 0x68
#define TELEMETRY_PERIOD_MS 30000